version: "3"

services:

  app:
    image: apple-health-data-workflow:latest
    environment:
      INGESTER_SOURCE_DIRECTORY: /data
      INGESTER_DESTINATION_USER: username
      INGESTER_DESTINATION_PASSWORD: password
      INGESTER_DESTINATION_HOST: warehouse
      INGESTER_DESTINATION_PORT: 5432
      INGESTER_DESTINATION_DATABASE: appleHealth
    volumes:
      - ${PWD}/data:/data:ro
    depends_on:
      warehouse:
        condition: service_healthy

  warehouse:
    image: postgres:16.2
    environment:
      POSTGRES_DB: appleHealth
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
