version: "3"

services:

  frontend:
    image: apple-health-data-workflow:latest
    command: /go/bin/frontend
    environment:
      WAREHOUSE_USER: username
      WAREHOUSE_PASSWORD: password
      WAREHOUSE_HOST: warehouse
      WAREHOUSE_PORT: 5432
      WAREHOUSE_DATABASE: apple_health
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    image: apple-health-data-workflow:latest
    command: /go/bin/backend
    environment:
      INGESTER_SOURCE_DIRECTORY: /data
      INGESTER_DESTINATION_USER: username
      INGESTER_DESTINATION_PASSWORD: password
      INGESTER_DESTINATION_HOST: warehouse
      INGESTER_DESTINATION_PORT: 5432
      INGESTER_DESTINATION_DATABASE: apple_health
    volumes:
      - ${PWD}/data:/data:ro
    depends_on:
      migration:
        condition: service_completed_successfully

  migration:
    image: redgate/flyway
    command: migrate
    volumes:
      - ${PWD}/migrations/flyway.toml:/flyway/conf/flyway.toml:ro
      - ${PWD}/migrations/sql:/flyway/sql:ro
    depends_on:
      warehouse:
        condition: service_healthy

  warehouse:
    image: postgres:16.2
    environment:
      POSTGRES_DB: apple_health
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
